---
# lds-bde-loader Configuration
#
# All commented values are the application default
#

### Path where BDE job files are stored
job_path: /home/lds_bde/.lds-bde-loader

### Enable debugging behaviours
debug: false

koordinates:
    ### API token
    api_token: {API_TOKEN}

    ### Endpoint
    endpoint: data.linz.govt.nz


### If you're running on a BDE Processor, you need to uncomment and fill in
### this section.
bde:
    ### BDE Processor database access details. Needs "bde_user" role
    database:
        host: {PGHOST}
        port: {PGPORT}
        database: {PGDATABASE}
        user: {PGUSER}
        password: {PGPASS}

    ### Mapping between BDE Database tables & Koordinates Layer IDs
    tables:
        ### LayerID : schema.table
        50771: lds.hydro_parcels
        50777: lds.survey_network_marks
        50780: lds.strata_parcels
        50788: lds.geodetic_antarctic_vertical_marks
        50778: lds.survey_arc_observations
        50782: lds.non_primary_parcels
        50783: lds.non_primary_linear_parcels
        50786: lds.geodetic_network_marks
        50785: lds.land_districts
        50789: lds.geodetic_antarctic_marks
        50784: lds.geodetic_vertical_marks
        50787: lds.geodetic_marks
        50776: lds.survey_non_bdy_marks
        50790: lds.cadastral_adjustments
        50772: lds.primary_parcels
        50794: lds.survey_plans
        50796: lds.road_parcels
        50774: lds.survey_bdy_marks
        50804: lds.titles
        50823: lds.land_parcels
        50820: lds.parcel_vectors
        50836: lds.waca_adjustments
        50835: lds.spi_adjustments
        50839: lds.survey_protected_marks
        50805: lds.titles_plus
        50806: lds.title_owners
        51564: lds.title_owners_aspatial
        51565: lds.parcel_stat_actions
        51566: lds.title_estates
        51567: lds.titles_aspatial
        51568: lds.affected_parcel_surveys
        51569: lds.title_parcel_associations
        51570: lds.all_linear_parcels
        51571: lds.all_parcels
        51590: bde.crs_appellation
        51593: bde.crs_sys_code_group
        51648: bde.crs_sys_code
        51694: lds.survey_observations
        51695: lds.title_memorials
        51696: lds.title_memorial_additional_text
        51698: bde.crs_statute_action
        51699: bde.crs_statute
        51700: bde.crs_stat_act_parcl
        51702: bde.crs_action
        51703: bde.crs_adj_user_coef
        51704: bde.crs_adjust_coef
        51705: bde.crs_adjust_method
        51706: bde.crs_adoption
        51707: bde.crs_affected_parcl
        51708: bde.crs_comprised_in
        51709: bde.crs_coordinate_sys
        51710: bde.crs_coordinate_tpe
        51711: bde.crs_cor_precision
        51712: bde.crs_cord_order
        51713: bde.crs_datum
        51714: bde.crs_elect_place
        51715: bde.crs_ellipsoid
        51717: bde.crs_legal_desc_prl
        51718: bde.crs_locality
        51723: bde.crs_parcel_bndry
        51724: bde.crs_obs_accuracy
        51725: bde.crs_observation
        51727: bde.crs_mark_sup_doc
        51728: bde.crs_action_type
        51729: bde.crs_node_works
        51730: bde.crs_obs_elem_type
        51731: bde.crs_obs_set
        51732: bde.crs_obs_type
        51733: bde.crs_off_cord_sys
        89377: bde.crs_ordinate_adj
        51735: bde.crs_ordinate_type
        51736: bde.crs_reduct_meth
        51737: bde.crs_reduct_run
        51738: bde.crs_ref_survey
        51742: bde.crs_setup
        51743: bde.crs_site
        51744: bde.crs_site_locality
        51746: bde.crs_sur_admin_area
        51747: bde.crs_sur_plan_ref
        51748: bde.crs_unit_of_meas
        51976: bde_ext.parcel
        51975: bde_ext.line
        51977: bde_ext.parcel_ls
        51979: bde_ext.vector_ls
        51980: bde_ext.vector_pt
        51981: bde_ext.adjustment_run
        51982: bde_ext.alias
        51985: bde_ext.encumbrancee
        51983: bde_ext.enc_share
        51984: bde_ext.encumbrance
        51988: bde_ext.maintenance
        51989: bde_ext.mark
        51986: bde_ext.legal_desc
        51991: bde_ext.mark_name
        51993: bde_ext.node
        51994: bde_ext.nominal_index
        51990: bde_ext.mark_phys_state
        51992: bde_ext.node_prp_order
        51996: bde_ext.parcel_label
        51997: bde_ext.parcel_ring
        51995: bde_ext.parcel_dimen
        52000: bde_ext.statist_area
        51998: bde_ext.proprietor
        51999: bde_ext.stat_version
        52001: bde_ext.survey
        52006: bde_ext.title_memorial
        52002: bde_ext.title_action
        52004: bde_ext.title_doc_ref
        52008: bde_ext.title_parcel_association
        52007: bde_ext.title_mem_text
        52010: bde_ext.ttl_enc
        52009: bde_ext.transact_type
        52012: bde_ext.ttl_inst
        52013: bde_ext.ttl_inst_title
        52011: bde_ext.ttl_hierarchy
        52014: bde_ext.work
        52016: bde_ext.feature_name_poly
        52017: bde_ext.feature_name_pt
        52018: bde_ext.coordinate
        52062: bde_ext.user
        52065: bde_ext.estate_share
        52066: bde_ext.office
        52067: bde_ext.title
        52068: bde_ext.title_estate
        52069: bde_ext.survey_plan_image_revision
        52070: bde.crs_land_district
        53389: lds.all_parcels_pend
        53422: lds.affected_parcel_surveys_pend
        95045: bde_ext.ttl_inst_cmplte

    ### Publish Groups to create
    ### These are started in the order below
    groups:
        - name: roads-addresses
          schedule: 'FREQ=WEEKLY;BYWEEKDAY=SA'  # Saturdays
          layers:
              ### Koordinates Layer IDs
              - 51714

        - name: parcels-topo-titles-memorials
          schedule: 'FREQ=WEEKLY;BYWEEKDAY=SA'  # Saturdays
          layers:
              - 51982
              - 51984
              - 51983
              - 51985
              - 52065
              - 51994
              - 51998
              - 52067
              - 52004
              - 52010
              - 52068
              - 52011
              - 52012
              - 52013
              - 52009
              - 51702
              - 51728
              - 52002
              - 52006
              - 52007
              - 51977
              - 51996
              - 52016
              - 51976
              - 52017
              - 51590
              - 51986
              - 51717
              - 51699
              - 51698
              - 51700
              - 52008
              - 51975
              - 51723
              - 51997
              - 95045

        - name: survey-obs-marks
          schedule: 'FREQ=WEEKLY;BYWEEKDAY=SA'  # Saturdays
          layers:
              - 51980
              - 51979
              - 51725
              - 51993
              - 51704
              - 51705
              - 51981
              - 51703
              - 52018
              - 51988
              - 51989
              - 51991
              - 51990
              - 51727
              - 51992
              - 51729
              - 51743
              - 51744
              - 51747
              - 51706
              - 51707
              - 51708
              - 51724
              - 51730
              - 51731
              - 51732
              - 51995
              - 51736
              - 51737
              - 51738
              - 51742
              - 52000
              - 51999
              - 52001
              - 51746
              - 52069
              - 52014
              - 89377

        - name: system-shared
          schedule: 'FREQ=WEEKLY;BYWEEKDAY=SA'  # Saturdays
          layers:
              - 52070
              - 51718
              - 51712
              - 51711
              - 51709
              - 51710
              - 51713
              - 51715
              - 51735
              - 51648
              - 51593
              - 51748
              - 52066
              - 52062
              - 51733

        - name: simple-parcel-title
          schedule: 'FREQ=WEEKLY;BYWEEKDAY=SA'  # Saturdays
          layers:
              - 51570
              - 50783
              - 50780
              - 50771
              - 50806
              - 50782
              - 50805
              - 50796
              - 51571
              - 50823
              - 50772
              - 50804
              - 51565
              - 51566
              - 51567
              - 51564
              - 51568
              - 51696
              - 51695
              - 51569
              - 53389
              - 53422

        - name: simple-survey
          schedule: 'FREQ=WEEKLY;BYWEEKDAY=SA'  # Saturdays
          layers:
              - 50839
              - 50788
              - 50789
              - 50787
              - 50786
              - 50784
              - 50785
              - 50774
              - 50794
              - 50820
              - 50777
              - 50776
              - 50790
              - 51694
              - 50778
              - 50835
              - 50836

logging:
    ### Python logging.dictConfig structure
    version: 1
    disable_existing_loggers: false
    formatters:
        console:
            format: "%(levelname)s [%(name)s]: %(message)s"
        logfile:
            format: "%(asctime)s %(name)s[%(process)d] %(module)s:%(lineno)d %(message)s"

    handlers:
        console:
            class: logging.StreamHandler
            # This is modified by --verbose/--quiet
            level: WARN
            formatter: console
            stream: ext://sys.stderr

        logfile:
            class: logging.handlers.RotatingFileHandler
            level: DEBUG
            formatter: logfile
            filename: /var/log/lds-bde-loader/lds-bde-loader.log
            maxBytes: 10485760  # 10MB
            backupCount: 30
            encoding: utf8

        email:
            class: ldsbde.core.util.EmailLogHandler
            mailhost: {EMAIL_HOST}
            subject: "LDS BDE Update - data.linz.govt.nz %(subject)s"
            fromaddr: {EMAIL_FROM}
            toaddrs: {EMAIL_LIST}

        slack:
            class: ldsbde.core.util.SlackLogHandler
            level: INFO
            api_key: {SLACK_TOKEN}
            channel: {SLACK_CHANNEL}
            icon_emoji: ":linz:"
            username: "Production BDE Loader"
            alert_errors: true

        pagerduty:
            class: ldsbde.core.util.EmailLogHandler
            level: ERROR
            mailhost: {EMAIL_HOST}
            subject: "LDSL BDE Update %(levelname)s Job#%(job_id)s"
            fromaddr: {EMAIL_FROM}
            toaddrs: {EMAIL_LIST}

    loggers:
        notify:
            handlers: [slack, pagerduty]
            propagate: false

        email:
            handlers: [email]
            propagate: false

    root:
        level: DEBUG
        handlers: [console, logfile]
